# Generated by Django 6.1 on 2026-08-27 18:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=6)),
                ('number', models.PositiveIntegerField()),
                ('full_number', models.CharField(max_length=20, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('order_capture', 'Order capture'), ('platform_commission', 'Platform commission'), ('vendor_settlement', 'Vendor settlement'), ('courier_payout', 'Courier payout'), ('refund_out', 'Refund out'), ('adjustment', 'Adjustment')], max_length=20)),
                ('payee_type', models.CharField(max_length=10)),
                ('payee_id', models.BigIntegerField(blank=True, null=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('batch_uuid', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('cod', 'Cash on delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=10)),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('amount_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('state', models.CharField(choices=[('initiated', 'Initiated'), ('requires_action', 'Requires action'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('voided', 'Voided')], default='initiated', max_length=16)),
                ('brand_last4', models.CharField(blank=True, max_length=4)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(choices=[('mistake', 'Mistake'), ('item_issue', 'Item issue'), ('late', 'Late'), ('no_show', 'No show'), ('goodwill', 'Goodwill')], max_length=12)),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='requested', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=10)),
                ('event_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('dead', 'Dead')], default='received', max_length=10)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_psp_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['initiated', 'requires_action', 'authorized'])), fields=('order',), name='one_live_payment_per_order'),
        ),
    ]
