[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Afzal20", email = "afzalhossen2019@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dj-database-url>=3.1.2",
    "dj-rest-auth[socialaccount]>=7.2.0",
    "django>=6.1",
    "django-allauth[socialaccount]>=65.19.1",
    "django-cors-headers>=4.9.0",
    "django-googledrive-storage>=1.6.0",
    "django-notifications-hq>=1.8.3",
    "django-redis>=7.0.0",
    "django-unfold>=0.104.1",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt[crypto]>=5.5.1",
    "drf-spectacular>=0.30.0",
    "faker>=40.37.0",
    "gunicorn>=26.2.0",
    "openai>=3.6.0",
    "psycopg>=3.3.4",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "supabase>=2.31.0",
    "whitenoise>=6.12.0",
]

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
