# Generated by Django 6.1 on 2026-08-29 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('drops', models.PositiveIntegerField(default=0)),
                ('earnings_minor', models.BigIntegerField(default=0)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='delivery.courierprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('courier', 'date'), name='unique_courier_day')],
            },
        ),
        migrations.CreateModel(
            name='DailyBranchMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('gmv_minor', models.BigIntegerField(default=0)),
                ('aov_minor', models.BigIntegerField(default=0)),
                ('completion_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('cancels_by_reason', models.JSONField(blank=True, default=dict)),
                ('avg_accept_secs', models.PositiveIntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='vendors.branch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'branch'), name='unique_daily_branch')],
            },
        ),
    ]
