# Generated by Django 6.1 on 2026-09-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_item_extra_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='local_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
