# Generated by Django 6.1 on 2026-08-27 18:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('ready', 'Ready for pickup'), ('picked', 'Picked up'), ('out', 'Out for delivery'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled_customer', 'Cancelled by customer'), ('cancelled_restaurant', 'Cancelled by restaurant'), ('cancelled_platform', 'Cancelled by platform'), ('failed_payment', 'Failed payment'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded')], db_index=True, default='placed', max_length=20)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('items_total_minor', models.BigIntegerField(default=0)),
                ('discount_minor', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_fee_minor', models.BigIntegerField(default=0)),
                ('vat_minor', models.BigIntegerField(default=0)),
                ('tip_minor', models.BigIntegerField(default=0)),
                ('grand_total_minor', models.BigIntegerField(default=0)),
                ('address', models.JSONField(default=dict)),
                ('coupon', models.JSONField(blank=True, default=dict)),
                ('eta', models.JSONField(blank=True, default=dict)),
                ('placed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendors.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveBigIntegerField()),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('actor_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('courier', 'Courier'), ('system', 'System'), ('operator', 'Operator')], max_length=10)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ('seq',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_ref', models.BigIntegerField()),
                ('title_snapshot', models.CharField(max_length=150)),
                ('qty', models.PositiveSmallIntegerField()),
                ('unit_price_minor', models.BigIntegerField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('line_total_minor', models.BigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('endpoint', models.CharField(max_length=100)),
                ('response', models.JSONField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('key', ''), _negated=True), fields=('user', 'key'), name='unique_idempotency_key')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status', '-placed_at'], name='orders_orde_custome_2c575b_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderevent',
            constraint=models.UniqueConstraint(fields=('order', 'seq'), name='unique_order_seq'),
        ),
    ]
